import os
from typing import Dict, Any, List

from app.rag.vector_store import vector_store
from app.sandbox.python_sandbox import python_sandbox
from app.core.config import settings

class ToolRegistry:
    """
    Registry of tools accessible by sovereign agents.
    Includes knowledge search, Python sandbox, DOCX, PPTX, and XLSX exporters.
    """
    def search_knowledge(self, query: str) -> Dict[str, Any]:
        results = vector_store.search(query)
        return {"status": "success", "query": query, "results": results}

    def execute_python_code(self, code: str) -> Dict[str, Any]:
        return python_sandbox.execute(code)

    def generate_docx(self, filename: str, title: str, sections: List[Dict[str, str]]) -> Dict[str, Any]:
        output_path = os.path.join(settings.WORKSPACES_DIR, filename)
        try:
            from docx import Document as DocxDocument
            doc = DocxDocument()
            doc.add_heading(title, 0)
            for sec in sections:
                doc.add_heading(sec.get("heading", "Section"), level=1)
                doc.add_paragraph(sec.get("content", ""))
            doc.save(output_path)
        except ImportError:
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(f"# {title}\n\n" + "\n".join([f"## {s.get('heading')}\n{s.get('content')}" for s in sections]))
        return {"status": "success", "file_path": output_path, "filename": filename}

    def generate_pptx(self, filename: str, title: str, slides: List[Dict[str, str]]) -> Dict[str, Any]:
        output_path = os.path.join(settings.WORKSPACES_DIR, filename)
        try:
            from pptx import Presentation
            prs = Presentation()
            slide = prs.slides.add_slide(prs.slide_layouts[0])
            slide.shapes.title.text = title
            slide.placeholders[1].text = "Generated by Sovereign AI Workbench"
            for s in slides:
                slide = prs.slides.add_slide(prs.slide_layouts[1])
                slide.shapes.title.text = s.get("title", "Slide")
                slide.placeholders[1].text = s.get("content", "")
            prs.save(output_path)
        except ImportError:
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(f"PRESENTATION: {title}\n" + "\n".join([f"SLIDE: {s.get('title')}\n{s.get('content')}" for s in slides]))
        return {"status": "success", "file_path": output_path, "filename": filename}

    def generate_xlsx(self, filename: str, headers: List[str], rows: List[List[Any]]) -> Dict[str, Any]:
        output_path = os.path.join(settings.WORKSPACES_DIR, filename)
        try:
            import openpyxl
            wb = openpyxl.Workbook()
            ws = wb.active
            ws.title = "Analysis Report"
            ws.append(headers)
            for r in rows:
                ws.append(r)
            wb.save(output_path)
        except ImportError:
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(",".join(headers) + "\n" + "\n".join([",".join([str(x) for x in r]) for r in rows]))
        return {"status": "success", "file_path": output_path, "filename": filename}

tool_registry = ToolRegistry()
